routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('after-register','Auth\RegisterController@afterRegister')->name('register.after');


Route::group(['middleware' => ['auth']], function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::match(['post','get'],'/', 'HomeController@index')->name('homeTest');
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::patch('users/{user}/update-pass','UserController@updatePass')->name('users.updatePass');
    Route::get('users/{user}/edit-pass','UserController@editPass')->name('users.editPass');
    Route::get('me/user-profile','UserController@profile')->name('users.profile');
    Route::get('me/edit-profile','UserController@editProfile')->name('users.editProfile');
    Route::post('me/update-profile','UserController@updateProfile')->name('users.updateProfile');
    Route::get('me/edit-profile-password','UserController@editProfilePass')->name('users.editProfilePass');
    Route::post('me/update-profile-password','UserController@updateProfilePass')->name('users.updateProfilePass');
    Route::resource('products','ProductController');
    Route::resource('type2s','Type2Controller');

    Route::resource('models','ModelController');
    Route::get('models-export-excel', 'ModelController@exportExcel')->name('models.exportExcel');

    Route::resource('files','FileController')->only([
        'index', 'show', 'edit', 'update','destroy'
    ]);
    // File + Document Route
    Route::post('files/dropzone-store', ['as'=>'files.dropzoneStore','uses'=>'FileController@dropzoneStore']);
    Route::delete('files/dropzone-delete/{fileName}', ['as'=>'files.dropzoneDelete','uses'=>'FileController@dropzoneDelete']);
    Route::get('files/{file}/download', ['as'=>'files.download','uses'=>'FileController@download']);

    // Document Route
    Route::resource('documents', 'DocumentController');
    Route::get('documents/{document}/approve', 'DocumentController@approve')->name('documents.approve');
    Route::delete('documents/{document}/reject', 'DocumentController@reject')->name('documents.reject');
    Route::get('documents/{document}/preview', 'DocumentController@preview')->name('documents.preview');
    Route::get('documents/{document}/preview-part', 'DocumentController@previewPart')->name('documents.previewPart');
    Route::get('documents/{document}/pdf', 'DocumentController@printPdf')->name('documents.printPdf');
    Route::get('documents/{document}/pdf/download', 'DocumentController@downloadPdf')->name('documents.downloadPdf');
    Route::get('documents-export-excel', 'DocumentController@exportExcel')->name('documents.exportExcel');
    Route::get('documents/{document}/files/edit', 'DocumentController@editFiles')->name('documents.editFiles');
    Route::post('documents/{document}/files/update', 'DocumentController@updateFiles')->name('documents.updateFiles');

    // AJAX route
    Route::get('member/ajaxSearch', ['as' => 'member.ajaxSearch', 'uses' => 'MemberController@ajaxSearch']);
    Route::get('ajax-inventory','InventoryController@ajaxSearch')->name('ajax.inventorySearch');
    Route::get('ajax-category','ModelController@ajaxCategory')->name('ajax.category');
//    Route::get('ajax-member','MemberController@ajaxSearch')->name('ajax.member');

    // Inventory route
    Route::get('inventory/list-inventory', ['as' => 'inventory.index', 'uses' => 'InventoryController@index']);
    Route::get('inventory/create', ['as' => 'inventory.create', 'uses' => 'InventoryController@create']);
    Route::post('inventory/store', ['as' => 'inventory.store', 'uses' => 'InventoryController@store']);
    Route::put('inventory/update/{id}', ['as' => 'inventory.update', 'uses' => 'InventoryController@update']);
    Route::get('inventory/show/{id}', ['as' => 'inventory.show', 'uses' => 'InventoryController@show']);
    Route::get('inventory/edit/{id}', ['as' => 'inventory.edit', 'uses' => 'InventoryController@edit']);
    Route::delete('inventory/destroy/{id}', ['as' => 'inventory.destroy', 'uses' => 'InventoryController@destroy']);
    Route::get('inventory/import', ['as' => 'inventory.import', 'uses' => 'InventoryController@import']);
    Route::post('inventory/handleExcel', ['as' => 'inventory.handleExcel', 'uses' => 'InventoryController@handleExcel']);
    Route::post('inventory/saveDataExcel', ['as' => 'inventory.saveDataExcel', 'uses' => 'InventoryController@saveDataExcel']);
    Route::get('inventory/getType2s', ['as' => 'inventory.getType2s', 'uses' => 'InventoryController@getType2s']);
    Route::get('inventory/getModelName', ['as' => 'inventory.getModelName', 'uses' => 'InventoryController@getModelName']);
    Route::post('inventory/exportFile', ['as' => 'inventory.exportFile', 'uses' => 'InventoryController@exportFile']);
//inventory/import


    // Member route
    Route::get('member/list-member', ['as' => 'member.index', 'uses' => 'MemberController@index']);
    Route::get('member/create', ['as' => 'member.create', 'uses' => 'MemberController@create']);
    Route::post('member/store', ['as' => 'member.store', 'uses' => 'MemberController@store']);
    Route::put('member/update/{id}', ['as' => 'member.update', 'uses' => 'MemberController@update']);
    Route::get('member/show/{id}', ['as' => 'member.show', 'uses' => 'MemberController@show']);
    Route::get('member/edit/{id}', ['as' => 'member.edit', 'uses' => 'MemberController@edit']);
    Route::delete('member/destroy/{id}', ['as' => 'member.destroy', 'uses' => 'MemberController@destroy']);
    Route::get('member-export-excel', 'MemberController@exportExcel')->name('member.exportExcel');
    Route::get('member/import', 'MemberController@import')->name('member.import');
    Route::post('member/handleExcel', ['as' => 'member.handleExcel', 'uses' => 'MemberController@handleExcel']);
    Route::post('member/saveDataExcel', ['as' => 'member.saveDataExcel', 'uses' => 'MemberController@saveDataExcel']);
    Route::post('member/exportFile', ['as' => 'member.exportFile', 'uses' => 'MemberController@exportFile']);

    // Unit route
    Route::get('unit/list-unit', ['as' => 'unit.index', 'uses' => 'UnitController@index']);
    Route::get('unit/create', ['as' => 'unit.create', 'uses' => 'UnitController@create']);
    Route::post('unit/store', ['as' => 'unit.store', 'uses' => 'UnitController@store']);
    Route::put('unit/update/{id}', ['as' => 'unit.update', 'uses' => 'UnitController@update']);
    Route::get('unit/show/{id}', ['as' => 'unit.show', 'uses' => 'UnitController@show']);
    Route::get('unit/edit/{id}', ['as' => 'unit.edit', 'uses' => 'UnitController@edit']);
    Route::delete('unit/destroy/{id}', ['as' => 'unit.destroy', 'uses' => 'UnitController@destroy']);

});

app/Type2.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Type2 extends Model
{
    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','type1_id'
    ];

    public function type1() {
        return $this->belongsTo('App\Type1');
    }

}

app/Type2s.php
<?php
/**
 * Created by PhpStorm.
 * User: conguyen
 * Date: 2019-03-03
 * Time: 09:18
 */

namespace App;
use Illuminate\Database\Eloquent\Model;


class Type2s extends Model
{
    protected $table = 'type2s';
}

app/Http/Controllers/Type2Controller.php
<?php

namespace App\Http\Controllers;

use App\Type1;
use App\Type2;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;

class Type2Controller extends Controller
{

    function __construct()
    {
        $this->middleware('permission:config-list',['only' => ['index','show']]);
        $this->middleware('permission:config-create', ['only' => ['create','store']]);
        $this->middleware('permission:config-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:config-delete', ['only' => ['destroy']]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $rowNum = config('constant.ROW_NUM_IN_PAGE');
        $query = Type2::query();
        if (!empty($request->name)) {
            $query->where('name','like', '%'.$request->name.'%');
        }
        if (!empty($request->type1_id) && $request->type1_id != -1) {
            $query->where('type1_id', $request->type1_id);
        }
        $type2s = $query->latest()->paginate($rowNum);

        $type1s = Type1::pluck('name','id')->all();
        $type1s[-1] = 'All';
        $inputs = Input::query();
        return view('type2s.index',compact('type2s','type1s','inputs'))
            ->with('i', (request()->input('page', 1) - 1) * $rowNum);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $type1s = Type1::pluck('name','id')->all();
        return view('type2s.create', compact('type1s'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required',
            'type1_id' => 'required',
        ]);


        Type2::create($request->all());


        return redirect()->route('type2s.index')
            ->with('success','Type2 created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Type2  $type2
     * @return \Illuminate\Http\Response
     */
    public function show(Type2 $type2)
    {
        return view('type2s.show',compact('type2'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Type2  $type2
     * @return \Illuminate\Http\Response
     */
    public function edit(Type2 $type2)
    {
        $type1s = Type1::pluck('name','id')->all();
        return view('type2s.edit',compact('type2','type1s'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Type2 $type2
     * @return void
     */
    public function update(Request $request, Type2 $type2)
    {
        request()->validate([
            'name' => 'required',
            'type1_id' => 'required',
        ]);


        $type2->update($request->all());


        return redirect()->route('type2s.index')
            ->with('success','Type2s updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Type2 $type2
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Type2 $type2)
    {
        $type2->delete();

        return redirect()->route('type2s.index')
            ->with('success','Type2 deleted successfully');
    }
}

resources/views/type2s/create.blade.php
@extends('layouts.master')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Type2</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('type2s.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @include('inc.input_alert')

    {!! Form::open(array('route' => 'type2s.store','method'=>'POST')) !!}
    @csrf
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Type1:</strong>
                <br/>
                {!! Form::select('type1_id', $type1s,null, array('class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
    {!! Form::close() !!}



@endsection

resources/views/type2s/edit.blade.php
@extends('layouts.master')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Type2</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('type2s.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @include('inc.input_alert')

    <form action="{{ route('type2s.update',$type2->id) }}" method="POST">
        @csrf
        @method('PUT')
               <div class="row">
                   <div class="col-md-6 col-12">
                       <div class="row">
                           <div class="col-xs-12 col-sm-12 col-md-12">
                               <div class="form-group">
                                   <strong>Name:</strong>
                                   {!! Form::text('name', $type2->name, array('placeholder' => 'Name','class' => 'form-control')) !!}
                               </div>
                           </div>
                           <div class="col-xs-12 col-sm-12 col-md-12">
                               <div class="form-group">
                                   <strong>Type1:</strong>
                                   <br/>
                                   {!! Form::select('type1_id', $type1s,$type2->type1_id, array('class' => 'form-control')) !!}
                               </div>
                           </div>
                           {{--<div class="col-xs-12 col-sm-12 col-md-12">--}}
                               {{--<div class="form-group">--}}
                                   {{--<strong>Created at:</strong>--}}
                                   {{--{!! Form::text('create_at', $type2->created_at, array('placeholder' => 'Created At','class' => 'form-control','disabled')) !!}--}}
                               {{--</div>--}}
                           {{--</div>--}}

                           {{--<div class="col-xs-12 col-sm-12 col-md-12">--}}
                               {{--<div class="form-group">--}}
                                   {{--<strong>Updated At:</strong>--}}
                                   {{--{!! Form::text('updated_at', $type2->updated_at, array('placeholder' => 'Updated At','class' => 'form-control','disabled')) !!}--}}
                               {{--</div>--}}
                           {{--</div>--}}
                           <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                               <button type="submit" class="btn btn-primary">Submit</button>
                           </div>
                       </div>
                   </div>
               </div>
    </form>
@endsection

resources/views/type2s/index.blade.php
@extends('layouts.master')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Type2s</h2>
            </div>
            <div class="pull-right">
                @can('config-create')
                    <a class="btn btn-success" href="{{ route('type2s.create') }}"> Create New Type2</a>
                @endcan
            </div>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-md-12">
            <form id="type2s-search-id" action="{{ route('type2s.index') }}">
                <div class="row align-middle">
                    <div class="col-xs-12 col-sm-12 col-md-4">
                        <div class="form-group">
                            <strong>Name:</strong>
                            {!! Form::text('name', $inputs['name'] ?? '', array('placeholder' => 'Name','class' => 'form-control','id' => 'name_input')) !!}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-4">
                        <div class="form-group">
                            <strong>Type1:</strong>
                            <br/>
                            {!! Form::select('type1_id', $type1s, $inputs['type1_id'] ?? -1 , array('class' => 'form-control','id' => 'type1_id_input')) !!}
                        </div>
                    </div>
                    <div>
                        {!! Form::input('hidden','page',null, ['id' => 'page_input_hidden']) !!}
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-2 text-center " style="vertical-align: middle;">
                        <button type="button" class="btn btn-primary type2s-search-ctrl" style="margin: 0 auto !important;	width: 100px;"><i class="fa fa-fw fa-search"></i>Search</button>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-2 text-center " style="vertical-align: middle;">
                        <button type="button" class="btn btn-light type2s-clear-ctrl" style="margin: 0 auto !important;	width: 100px;"><i class="fa fa-fw  fa-recycle"></i>Reset</button>
                    </div>
                </div>
            </form>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered mt-3">
        {{--<tbody style=" overflow-y:auto;">--}}
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Type1</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th width="280px">Action</th>
        </tr>
        @php
            $i = 0;
        @endphp
        @foreach ($type2s as $type2)

            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $type2->name }}</td>
                <td>{{ $type2->type1 == null ? 'N/A' : $type2->type1->name }}</td>
                <td>{{ $type2->created_at }}</td>
                <td>{{ $type2->updated_at }}</td>
                <td>
                    {{--<form action="{{ route('type2s.destroy',$type2->id) }}" method="POST">--}}
                        <a class="btn btn-info" href="{{ route('type2s.show',$type2->id) }}">Show</a>
                        @can('config-edit')
                            <a class="btn btn-primary" href="{{ route('type2s.edit',$type2->id) }}">Edit</a>
                        @endcan


                        {{--@csrf--}}
                        {{--@method('DELETE')--}}
                        @can('config-delete')
                            {{--<button type="submit" class="btn btn-danger">Delete</button>--}}
                            {!! Form::open(['method' => 'DELETE','route' => ['type2s.destroy', $type2->id],'style'=>'display:inline']) !!}
                            {!! Form::submit('Delete', ['class' => 'btn btn-danger','onclick' => 'return CustomJs.ConfirmDelete()']) !!}
                            {!! Form::close() !!}
                        @endcan
                    {{--</form>--}}
                </td>
            </tr>
        @endforeach
        {{--</tbody>--}}

    </table>


    {{--{!! $type2s->links() !!}--}}
    {!!  $type2s->appends($_GET)->links()  !!}



@endsection

@push('js')
    <script>
        $(function() {
            console.log( "ready!" );
            $('.type2s-search-ctrl').click(function(e) {
                e.preventDefault();
                console.log('aa')
                $('#page_input_hidden').val($('.pagination li.active span').html());
                $( "#type2s-search-id" ).submit();

            })

            $('.type2s-clear-ctrl').click(function(e) {
                e.preventDefault();
                $( "#name_input" ).val('');
                $( "#type1_id_input" ).val('-1');
                $('#page_input_hidden').val(1);
                $( "#type2s-search-id" ).submit();
            })
        });

    </script>
@endpush

resources/views/type2s/show.blade.php
@extends('layouts.master')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Type2</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('type2s.index') }}"> Back</a>
            </div>
        </div>
    </div>


    {{--<div class="row">--}}
        {{--<div class="col-xs-12 col-sm-12 col-md-12">--}}
            {{--<div class="form-group">--}}
                {{--<strong>Name:</strong>--}}
                {{--{{ $type2->name }}--}}
            {{--</div>--}}
        {{--</div>--}}
        {{--<div class="col-xs-12 col-sm-12 col-md-12">--}}
            {{--<div class="form-group">--}}
                {{--<strong>Type1:</strong>--}}
                {{--{{ $type2->type1_id }}--}}
            {{--</div>--}}
        {{--</div>--}}
        {{--<div class="col-xs-12 col-sm-12 col-md-12">--}}
            {{--<div class="form-group">--}}
                {{--<strong>Created At:</strong>--}}
                {{--{{ $type2->created_at }}--}}
            {{--</div>--}}
        {{--</div>--}}
        {{--<div class="col-xs-12 col-sm-12 col-md-12">--}}
            {{--<div class="form-group">--}}
                {{--<strong>Updated At:</strong>--}}
                {{--{{ $type2->updated_at }}--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</div>--}}

    <div class="row">
        <div class="col-12 col-md-6">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Name:</strong>
                        {!! Form::text('name', $type2->name, array('placeholder' => 'Name','class' => 'form-control','disabled')) !!}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Type1:</strong>
                        <br/>
                        {!! Form::text('type1_id', $type2->type1 == null ? '' : $type2->type1->name, array('placeholder' => 'Type1','class' => 'form-control','disabled')) !!}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Created at:</strong>
                        {!! Form::text('create_at', $type2->created_at, array('placeholder' => 'Created At','class' => 'form-control','disabled')) !!}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Updated At:</strong>
                        {!! Form::text('updated_at', $type2->updated_at, array('placeholder' => 'Updated At','class' => 'form-control','disabled')) !!}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <a type="button" class="btn btn-primary" href="{{route('type2s.edit',$type2->id)}}">Edit</a>
                </div>

            </div>
        </div>
    </div>

@endsection